project:
  type: website
  output-dir: docs

website:
  title: "Cole Kehrberg"

  navbar:
    left:
      - href: index.qmd
        text: Home
      - sidebar:stats
      - sidebar:economics
      - sidebar:environmental
      - sidebar:personal

  sidebar:
    - id: stats
      title: "Statistics & Data Science Projects"
      contents:
        - about.qmd
        - maps.qmd

    - id: economics
      title: "Economics Projects"
      contents:
        - ECON385.qmd

    - id: environmental
      title: "Environmental Studies Projects"
      contents: []

    - id: personal
      title: "Personal Projects"
      contents: []

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
    page-layout: full