project:
  type: website
  output-dir: docs

website:
  title: "Cole Kehrberg"

  navbar:
    left:
      - href: index.qmd
        text: Home
      - sidebar:stats
      - sidebar:economics
      - sidebar:environmental
      - sidebar:personal

  sidebar:
    - id: stats
      title: "Statistics & Data Science"
      contents:
        - Stats/Stats2.qmd
        - Stats/about.qmd
        - Stats/maps.qmd

    - id: economics
      title: "Economics"
      contents:
        - Economics/ECON385.qmd
        - Economics/ECON372.qmd

    - id: environmental
      title: "Environmental Studies"
      contents:
         - Environmental_Studies/PEN.qmd
         - Environmental_Studies/GIS.qmd

    - id: personal
      title: "Personal Projects"
      contents:
         - Personal/FantasyBaseball.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
    page-layout: full